username: shouta
hostname: A3112
system: aarch64-darwin

git:
  name: shouta totsuka
  email: 5h0utat0t2uka@gmail.com
  signingKey: ""   # 任意

ghq:
  user: 5h0utat0t2uka
  root: ~/Development/repositories
