[[station]]
name = "Cliamp Lofi"
url = "https://radio.cliamp.stream/lofi/stream.pls"

[[station]]
name = "安住紳一郎の日曜天国"
url = "https://feeds.megaphone.fm/TBS2679398439"

# Lo-fi / Chill
[[station]]
name = "SomaFM Groove Salad"
url = "https://somafm.com/groovesalad.pls"

[[station]]
name = "SomaFM Groove Salad Classic"
url = "https://somafm.com/gsclassic.pls"

# Electronic / Ambient
[[station]]
name = "SomaFM Drone Zone"
url = "https://somafm.com/dronezone.pls"

[[station]]
name = "SomaFM Deep Space One"
url = "https://somafm.com/deepspaceone.pls"

[[station]]
name = "SomaFM Space Station Soma"
url = "https://somafm.com/spacestation.pls"
